spring:
  application:
    name: prescriptionService
  datasource:
    url: jdbc:mysql://127.0.10.11:3306/prescription
    username: root
    password: 123456
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083
  
management:
  tracing:
    sampling:
      probability: 0.0


