spring:
  application:
    name: prescriptionService
  datasource:
    url: jdbc:mysql://127.0.10.11:3306/prescription
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL8Dialect 

server:
  port: 8083
  
management:
  tracing:
    sampling:
      probability: 1.0


