spring:
  application:
    name: drugService
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://127.0.10.11:3306/drug
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL8Dialect
=======
    url:
    username: 
    password: 
    driver-class-name: 
>>>>>>> c16da9b4506cb0939a5bd0aebb25635cd8a025ea

server:
  port: 8084
  
management:
  tracing:
    sampling:
      probability: 1.0

