spring:
  application:
    name: drugService
  datasource:
    url: jdbc:mysql://127.0.10.11:3306/drug
    username: root
    password: 123456

eureka:
  client:
    enabled: false

server:
  port: 8084
  
management:
  tracing:
    sampling:
      probability: 0.0

